picturesque/config/routes.rb
Picturesque::Application.routes.draw do
  root :to => "galleries#index"

  resources :galleries
  resources :paintings
end

picturesque/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name
  has_many :paintings
end

picturesque/app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :gallery_id, :name, :image, :remote_image_url
  belongs_to :gallery
  mount_uploader :image, ImageUploader
end

picturesque/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

picturesque/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(params[:gallery])
    if @gallery.save
      flash[:notice] = "Successfully created gallery."
      redirect_to @gallery
    else
      render :action => 'new'
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update_attributes(params[:gallery])
      flash[:notice] = "Successfully updated gallery."
      redirect_to gallery_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    flash[:notice] = "Successfully destroyed gallery."
    redirect_to galleries_url
  end
end

picturesque/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def new
    @painting = Painting.new(:gallery_id => params[:gallery_id])
  end

  def create
    @painting = Painting.new(params[:painting])
    if @painting.save
      flash[:notice] = "Successfully created painting."
      redirect_to @painting.gallery
    else
      render :action => 'new'
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      flash[:notice] = "Successfully updated painting."
      redirect_to @painting.gallery
    else
      render :action => 'edit'
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    flash[:notice] = "Successfully destroyed painting."
    redirect_to @painting.gallery
  end
end

picturesque/app/helpers/application_helper.rb
module ApplicationHelper
end

picturesque/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

picturesque/app/helpers/galleries_helper.rb
module GalleriesHelper
end

picturesque/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

picturesque/app/helpers/paintings_helper.rb
module PaintingsHelper
end

picturesque/app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

picturesque/app/views/galleries/edit.html.erb
<% title "Edit Gallery" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @gallery %> |
  <%= link_to "View All", galleries_path %>
</p>

picturesque/app/views/galleries/index.html.erb
<% title "Galleries" %>

<% for gallery in @galleries %>
  <div class="gallery">
    <h2><%= link_to gallery.name, gallery %></h2>
    Paintings: <%= gallery.paintings.size %>
  </div>
<% end %>

<p><%= link_to "New Gallery", new_gallery_path %></p>

picturesque/app/views/galleries/new.html.erb
<% title "New Gallery" %>

<%= render 'form' %>

<p><%= link_to "Back to List", galleries_path %></p>

picturesque/app/views/galleries/show.html.erb
<% title @gallery.name %>

<div id="paintings">
  <% for painting in @gallery.paintings %>
    <div class="painting">
      <%= image_tag painting.image_url(:thumb) if painting.image? %>
      <div class="name"><%= painting.name %></div>
      <div class="actions">
        <%= link_to "edit", edit_painting_path(painting) %> |
        <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<p>
  <%= link_to "Add a Painting", new_painting_path(:gallery_id => @gallery) %> |
  <%= link_to "Remove Gallery", @gallery, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View Galleries", galleries_path %>
</p>

picturesque/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

picturesque/app/views/paintings/_form.html.erb
<%= form_for @painting, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :gallery_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

picturesque/app/views/paintings/edit.html.erb
<% title "Edit Painting" %>

<%= render 'form' %>

<p><%= link_to "Back to Gallery", @painting.gallery %></p>

picturesque/app/views/paintings/new.html.erb
<% title "New Painting" %>

<%= render 'form' %>

<p><%= link_to "Back to Gallery", @painting.gallery %></p>